### ISSUE TITLE
Typescript: Missing definition for 'nextPageParameters'

### ISSUE THREAD

**Issue by james-em** [MONEI/Shopify-api-node#405] opened 2020-08-07 12:55 UTC
**Steps to reproduce**

```
const products = await this.shopify.product.list(params);
...
params = products.nextPageParameters;
```

**Error**

```
Property 'nextPageParameters' does not exist on type 'IProduct[]'.
```

**Temporary fix I have to do**

```
// @ts-ignore
params = products.nextPageParameters;
```

**Definitive fix**

```
interface IProduct {
    ...
    nextPageParameters?: INextPageParameter; // or just put any at least
}

interface INextPageParameter {
  ... // whatever is in this interface
}

**Comment by lpinca** [comment] 2020-08-07 19:01
Duplicate of #288

**Closed by lpinca** 2020-08-07 19:01 UTC
