### ISSUE TITLE
Upgrading from 2.25.1 to 3.x results in ParseError 

### ISSUE THREAD

**Issue by flomllr** [MONEI/Shopify-api-node#386] opened 2020-06-28 11:28 UTC
I'm trying to update the package from version 2.25.1 to the latest version 3.3.2, but as soon as I do that, I get the following error on any call on the `shopify` instance:

```JSON
{
   "name":"ParseError",
   "timings":{
      "start":1593343057528,
      "socket":1593343057529,
      "lookup":1593343057539,
      "connect":1593343057541,
      "secureConnect":1593343057544,
      "upload":1593343057544,
      "response":1593343057719,
      "end":1593343057783,
      "phases":{
         "wait":1,
         "dns":10,
         "tcp":2,
         "tls":3,
         "request":0,
         "firstByte":175,
         "download":64,
         "total":255
      }
   }
}
```

Any idea what might cause that?

**Comment by lpinca** [comment] 2020-06-29 13:29
It means that the response body was not valid JSON.

**Comment by Art3miX** [comment] 2020-07-16 08:15
@lpinca I have the same issue, the only change I did was to update to 3.3.2, then I get the same error as above, when i revert back to 2.25.1 everything works fine (Except the timeout issue for a specific store #371)

Here is my stack:
```
RequestError: Unexpected token < in JSON at position 0 in "https://the-tool-shop.myshopify.com/admin/api/2020-04/themes.json"                                     
at Object.exports.parseBody (*/node_modules/got/dist/source/as-promise/core.js:29:15)                                    
at PromisableRequest.onResponse (*/node_modules/got/dist/source/as-promise/index.js:95:48)    
at JSON.parse (<anonymous>)                                                                                                                                   
at parseJson (*/node_modules/got/dist/source/index.js:118:35)   
at Object.exports.parseBody (*/node_modules/got/dist/source/as-promise/core.js:18:48)                                      
at PromisableRequest.onResponse (*/node_modules/got/dist/source/as-promise/index.js:95:48)   
at processTicksAndRejections (internal/process/task_queues.js:97:5) {                                                                                         
name: 'ParseError',                                                                                                                                             
code: undefined,                                                                                                                                                
timings: {                                                                                                                                                      
start: 1594886283539,                                                                                                                                         
socket: 1594886283542,                                                                                                                                        
lookup: 1594886283566,                                                                                                                                        
connect: 1594886283576,                                                                                                                                       
secureConnect: 1594886283589,                                                                                                                                 
upload: 1594886283589,                                                                                                                                        
response: 1594886283762,                                                                                                                                      
end: 1594886283894,               
```

If the response is not a valid JSON how come 2.25.1 is working without any issues when same code is used?

This is a major version change, is there a need for code change when we upgrade to 3.3.2?

**Comment by lpinca** [comment] 2020-07-16 14:19
> If the response is not a valid JSON how come 2.25.1 is working without any issues when same code is used?

I guess the request is different so the server sends a different response?

> This is a major version change, is there a need for code change when we upgrade to 3.3.2?

No, there are not API breaking changes.

**Comment by lpinca** [comment] 2020-07-16 14:29
I can't reproduce with `shopify-api-node@3.3.2`.

```
$ cat gh-386.js 
'use strict';

const Shopify = require('shopify-api-node');

const shopify = new Shopify({
  shopName: 'quuz',
  apiVersion: '2020-07',
  apiKey: 'b68c3a4bf44cd240511e5f4114f0be4d',
  password: '2d170167fc62551920ca60fe40a5e548'
});

(async function () {
  const themes = await shopify.theme.list();
  console.log(themes);
})().catch(console.error);
```

```
$ node gh-386.js 
[
  {
    id: 171370695,
    name: 'debut',
    created_at: '2017-04-26T03:47:08-04:00',
    updated_at: '2017-04-26T03:47:12-04:00',
    role: 'main',
    theme_store_id: 796,
    previewable: true,
    processing: false,
    admin_graphql_api_id: 'gid://shopify/Theme/171370695'
  }
]
```

**Comment by alexbouchardd** [comment] 2020-08-01 18:37
> It means that the response body was not valid JSON.

I'm facing the same issue as mentioned above. I still don't have a firm diagnostic but in my case, `shopify-api-node`/`got` is incorrectly requesting the homepage of the storefront and returning HTML text instead of api path which would return JSON.

**Comment by alexbouchardd** [comment] 2020-08-01 18:39
Downgrading to 2.25.1 worked for my local development on node v12.14.1. 3+ is causing the issue and logging `got` reveals the same issue as in https://github.com/MONEI/Shopify-api-node/issues/397

**Comment by Fauphi** [comment] 2020-08-03 11:00
I have the same problem after updating to 3.4.2 (node v10.22.0).

Downgrading to 2.25.1 works, but this version does not support the "nextPageParameters".

```
{ RequestError: Unexpected token < in JSON at position 0 in "https://dariadeh.myshopify.com/admin/orders.json?limit=250&created_at_min=2020-06-13T10%3A31%3A39.000Z&status=any"
    at Object.exports.parseBody (/Users/philipp/Development/wercship-mothership/app/mothership-api/node_modules/shopify-api-node/node_modules/got/dist/source/as-promise/core.js:29:15)
    at PromisableRequest.onResponse (/Users/philipp/Development/wercship-mothership/app/mothership-api/node_modules/shopify-api-node/node_modules/got/dist/source/as-promise/index.js:95:48)
    at JSON.parse (<anonymous>)
    at parseJson (/Users/philipp/Development/wercship-mothership/app/mothership-api/node_modules/shopify-api-node/node_modules/got/dist/source/index.js:118:35)
    at Object.exports.parseBody (/Users/philipp/Development/wercship-mothership/app/mothership-api/node_modules/shopify-api-node/node_modules/got/dist/source/as-promise/core.js:18:48)
    at PromisableRequest.onResponse (/Users/philipp/Development/wercship-mothership/app/mothership-api/node_modules/shopify-api-node/node_modules/got/dist/source/as-promise/index.js:95:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ParseError',
  code: undefined,
  timings:
   { start: 1596452226332,
     socket: 1596452226340,
     lookup: 1596452226341,
     connect: 1596452226353,
     secureConnect: 1596452226386,
     upload: 1596452226387,
     response: 1596452227251,
     end: 1596452227273,
     error: undefined,
     abort: undefined,
     phases:
      { wait: 8,
        dns: 1,
        tcp: 12,
        tls: 33,
        request: 1,
        firstByte: 864,
        download: 22,
        total: 941 } } }
```

**Comment by lpinca** [comment] 2020-08-03 13:13
@Fauphi I can't reproduce:

```
$ cat index.js 
'use strict';

const assert = require('assert');
const Shopify = require('shopify-api-node');

const shopify = new Shopify({
  shopName: 'quuz',
  apiVersion: '2020-07',
  apiKey: 'b68c3a4bf44cd240511e5f4114f0be4d',
  password: '2d170167fc62551920ca60fe40a5e548'
});

(async function () {
  let products = await shopify.product.list();

  assert.deepStrictEqual(products, []);

  const product = await shopify.product.create({
    body_html: '<strong>Good snowboard!</strong>',
    product_type: 'Snowboard',
    title: 'Burton Custom Freestlye 151',
    vendor: 'Burton'
  });

  products = await shopify.product.list({
    created_at_min: '2020-08-03T13:02:43.691Z',
    limit: 250
  });

  console.log(products);

  await shopify.product.delete(product.id);
})().catch(console.error);
```

```
$ npm ls --depth 0
/Users/luigi/Desktop/shopify-api-node-386
`-- shopify-api-node@3.4.2
```

```
$ docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app node:10.22.0-alpine node index.js
[ { id: 4614364299299,
    title: 'Burton Custom Freestlye 151',
    body_html: '<strong>Good snowboard!</strong>',
    vendor: 'Burton',
    product_type: 'Snowboard',
    created_at: '2020-08-03T09:12:07-04:00',
    handle: 'burton-custom-freestlye-151',
    updated_at: '2020-08-03T09:12:07-04:00',
    published_at: '2020-08-03T09:12:07-04:00',
    template_suffix: null,
    published_scope: 'web',
    tags: '',
    admin_graphql_api_id: 'gid://shopify/Product/4614364299299',
    variants: [ [Object] ],
    options: [ [Object] ],
    images: [],
    image: null } ]
```

**Comment by Fauphi** [comment] 2020-08-04 09:15
Ok, found the problem. 

There was some conflict with the [Sentry/node package](https://github.com/getsentry/sentry-javascript/tree/master/packages/node), updated that to the latest version, now everything works fine.

**Comment by alexbouchardd** [comment] 2020-08-04 14:28
Hey @Fauphi I tried updating that same lib without success, are you able to tell what got version your package.lock is showing?

**Comment by Fauphi** [comment] 2020-08-04 15:08
@alexbouchardd 

got - 5.7.1
sentry/node - 5.20.1

with node 10.22.0

**Comment by agarbund** [comment] 2020-09-01 13:45
@lpinca I have the same issue with parsing error and here is my `npm ls agent-base`:

```
├─┬ auth0@2.27.1
│ └─┬ rest-facade@1.13.0
│   └─┬ superagent-proxy@2.0.0
│     └─┬ proxy-agent@3.1.1
│       ├── agent-base@4.3.0  deduped
│       ├─┬ pac-proxy-agent@3.0.1
│       │ └── agent-base@4.3.0  deduped
│       └─┬ socks-proxy-agent@4.0.2
│         └── agent-base@4.2.1 
└─┬ sqreen@1.46.0
  ├─┬ http-proxy-agent@2.1.0
  │ └── agent-base@4.3.0 
  └─┬ https-proxy-agent@3.0.1
    └── agent-base@4.3.0  deduped
```

**Comment by lpinca** [comment] 2020-09-01 14:36
Yes, the problem is in `agent-base@<=4`. Version >= 5 is ok.

**Comment by lpinca** [comment] 2020-10-23 08:34
I'm closing as there is not much we can do. The issue has been fixed in `auth0` and `@sentry/node`. It is still present in `sqreen`.

**Closed by lpinca** 2020-10-23 08:34 UTC
