### ISSUE TITLE
Shopify.shop.get() `startsWith` error v.3.3.0

### ISSUE THREAD

**Issue by VaCool** [MONEI/Shopify-api-node#359] opened 2020-03-17 16:22 UTC
Error: Cannot read property 'startsWith' of undefined

**Comment by VaCool** [comment] 2020-03-17 16:24
got v10.6.0

**Comment by lpinca** [comment] 2020-03-17 18:09
Duplicate of https://github.com/MONEI/Shopify-api-node/issues/334

**Comment by lpinca** [comment] 2020-03-17 18:10
Try with a recent and supported Node.js version.

**Closed** 2020-03-21 05:43 UTC
