### ISSUE TITLE
Updating order

### ISSUE THREAD

**Issue by corbinu** [MONEI/Shopify-api-node#166] opened 2018-02-01 01:14 UTC
I am currently transitioning to this module. It works great other than when I attempt to put and order update (specifically alter the order notes). The transaction succeeds but the order is not actually updated on Shopify's end. 

I tried to find some reason for this in the codebase and came up empty. I can create a reproduction but would mean creating a private Shopify app and would need someway to securely let one of you maintainers have the credentials to install in a test store.

Thanks!

**Comment by lpinca** [comment] 2018-02-01 08:13
Does it work if you don't use this library? I mean, are the notes updated if you use `curl` or https://insomnia.rest/ or another HTTP client?

If it works we should see what's different in the request and fix it accordingly.

**Comment by corbinu** [comment] 2018-02-01 16:44
Yes it always worked when I was using the shopify-node module

**Comment by corbinu** [comment] 2018-02-01 16:47
This is what I was using before: https://www.npmjs.com/package/shopify-node

I have replaced all uses of it except for updating the order notes

**Comment by lpinca** [comment] 2018-02-01 17:45
I don't have a test shop and an app to debug this atm so I can only suggest you to inspect the request made by both modules and see where they differ. You can use a debugging proxy like Fiddler for example.

**Comment by corbinu** [comment] 2018-02-01 20:40
Ok will do

**Comment by olivej** [comment] 2018-02-05 06:40
I can confirm that I am having same problem.  I cannot update any fields on Draft Orders or Order objects (haven't tried any others).

**Comment by lpinca** [comment] 2018-02-05 08:18
I can't reproduce. Here is my test case using a private app.

```js
(async function () {
  const { note } = await shopify.order.update(orderId, {
    id: orderId,
    note: 'This is a note'
  });

  console.log(note);
})().catch((err) => console.log(err.response.body));
```

The order note is updated correctly. Changes are reflected in the admin dashboard.

**Comment by corbinu** [comment] 2018-02-05 12:00
@lpinca Sorry haven't had a chance to look at this yet been swamped all weekend. I should have been more clear it is note_attributes not note that I am trying to update.

**Comment by lpinca** [comment] 2018-02-05 12:02
Ok, I'll try again when I get a chance.

**Comment by corbinu** [comment] 2018-02-05 12:06
Thanks so much maybe I am just making some silly mistake but everything else dropped right in so is driving me crazy.

**Comment by lpinca** [comment] 2018-02-05 21:12
@corbinu I still can't reproduce. Here is the code

```js
const Shopify = require('shopify-api-node');
const { deepStrictEqual } = require('assert');

const shopify = new Shopify({
  shopName: 'redacted',
  apiKey: 'redacted',
  password: 'redacted'
});

function getNoteAttributes(orderId) {
  return shopify.order.get(orderId).then((order) => order.note_attributes);
}

(async function () {
  const id = 161875656716;
  const note_attributes = [];

  deepStrictEqual(await getNoteAttributes(id), note_attributes);

  note_attributes.push({ name: 'color', value: 'red' });
  await shopify.order.update(id, { id, note_attributes });
  deepStrictEqual(await getNoteAttributes(id), note_attributes);

  note_attributes[0].value = 'green'
  await shopify.order.update(id, { id, note_attributes });
  deepStrictEqual(await getNoteAttributes(id), note_attributes);

  note_attributes.length = 0;
  await shopify.order.update(id, { id, note_attributes });
  deepStrictEqual(await getNoteAttributes(id), note_attributes);
})().catch((err) => {
  console.error(err.response && err.response.body || err.stack);
});

```

**Comment by salhotra** [comment] 2018-02-06 09:16
I can confirm the same issue.
I am using google cloud functions for the callback on the 'create order' webhook in shopify. Everything was working correctly for the past 2 months. I made a change 2 days ago and re deployed my cloud function. Then all of a sudden order tags didn't get updated in the shopify dashboard. In the response I received 200 and the response object in the then() had the correct tags in the order object when I printed it in the console.
Then I removed this package and used shopify-node-api. I made the necessary config changes for that package it worked. Then I checked my firebase console and found 19 requests on my cloud function from shopify. So I looked at my code and I had forgot to send res status 200 to shopify after order update. I fixed this and the same problem emerged.
This is the code from the other package. (very similar to this package).
`Shopify.put(`/admin/orders/${orderId}.json`, data, (err, order) => {
    if (err) {
      console.log(err);
      response.sendStatus(400);
    }
    if (get(order, 'order.tags.length') !== 0) {
      response.sendStatus(200);
    }
  });`

Same functionality with this package:
` shopify.order.update(orderId, data)
    .then((orders) => {
      console.log(orders);
      response.sendStatus(200);
    })
    .catch(err => console.error(err));`

If we don't send 200 to shopify, it calls this function around 20 times and one of those times the tags are updated.

**Comment by lpinca** [comment] 2018-02-06 09:58
It doesn't make much sense. Your source of truth is the API. If the data in the dashboard isn't updated it may be a caching/front-end/dashboard issue. If you get the order after the update and the updated data it's there, the changes are applied.

**Comment by salhotra** [comment] 2018-02-06 10:03
@lpinca I agree that this doesn't look like a problem with this package. But if it is indeed a "caching/front-end/dashboard issue", then why does it work using postman or cUrl is what I am wondering.

**Comment by lpinca** [comment] 2018-02-06 10:42
From my tests it also works with lib, see https://github.com/MONEI/Shopify-api-node/issues/166#issuecomment-363222994.

**Comment by psema4** [comment] 2018-02-16 18:21
I started seeing something similar with the Products API this morning as well - the request would POST without error and without updating my products.

After reading this issue and digging through the library's source code without gaining new insight, I added a `console.log(util.inspect(options))` just before the return statement in Shopify.request() _[index.js @ line 121]_ and found the source of my trouble.

Turns out I had some code that was unexpectedly adding an extra layer around my product:

`{ product: { product: { title: 'foo' } } }`

**Comment by lpinca** [comment] 2018-02-16 18:56
@psema4 are you always ending your promise chain with `catch`? Shopify returns a 422 status code if submitted data is invalid and the promise is rejected.

**Comment by corbinu** [comment] 2018-02-17 21:05
Not exactly sure what did that fixed it but seems to be working now after a lot of fiddling sorry for taking up your time. Thanks so much for taking a look.

**Comment by lpinca** [comment] 2018-02-17 21:09
No problem, closing then.

**Closed by lpinca** 2018-02-17 21:09 UTC

**Comment by Harshpanday** [comment] 2023-06-15 20:38
Hey @lpinca ,
I recently started using this library and I am facing a similar issue.
I am trying to update the fulfillment_status of my order, but for some reason it is not getting updated.
Here is my code
```
const Shopify = require('shopify-api-node');
        const shopify = new Shopify({
            shopName: 'XXX.myshopify.com',
            apiKey: 'XXXX',
            password: 'XXXX',
          });

          const { orderId, fulfillmentStatus } = req.body;
          try {
            // Update the fulfillment status of the order
            const updatedOrder = await shopify.order.update(orderId, {
                id : orderId,
                fulfillment_status: "Fulfilled",
            });
            console.log(updatedOrder)
        }catch(e){
            console.log(e)
        }
```
In console, the order getting printed is the correct order but the fulfillment status is still `null`.
I would be grateful if you tell me what am I doing wrong.
