### ISSUE TITLE
Receiving error while trying to use SDK with Meteor

### ISSUE THREAD

**Issue by mikeacre** [MONEI/Shopify-api-node#406] opened 2020-08-13 12:27 UTC
Hey,

When I try to call the sdk I get the error:
"Exception while invoking method 'shop.get.customers' RequestError: Unexpected token < in JSON at position 0"
Which I assume is due to an authentication error. 

I used ShopToken to generate a code and then an access token. 

I am initializing the SDK as such:
`
const shopify = new Shopify({
    shopName: {STORE_NAME},
    apiKey: {API_KEY},
    password: {ACCESS_TOKEN},

});
`

The store name is the name of the store I authenticated with the token and have the access token for.

The api key is the one in my shopify partners dashboard that shows the app has been installed and has the appropriate permissions.

The Access Token is the one I generated after making the code with the correct permissions 

Any ideas what could be causing this?

**Comment by shank318** [comment] 2020-08-15 18:21
Is it resolved? I am getting the same

**Comment by mikeacre** [comment] 2020-08-15 19:00
No I’ve had to go back to using square for my projects for now.

**Comment by lpinca** [comment] 2020-08-18 05:42
Make sure `password` is the private app password and not the secret or the OAuth 2.0 access token.

**Comment by mikeacre** [comment] 2020-08-18 10:44
Thank you for the reply @lpinca , What is the password then?

> password - Required for private apps - A string that specifies the private app password. This option must be used in conjunction with the apiKey option and is **mutually exclusive with the accessToken option.**

Doest that mean the password is the Api Key?

**Comment by mikeacre** [comment] 2020-08-18 17:15
Still receiving the same error this way. But also doesn't this negate me making a private app and creating the access token? Is there no need for the access token at all then?

**Comment by mikeacre** [comment] 2020-08-18 17:15
I can create a simple http request using those credentials, but this does not work for the sdk.

**Comment by lpinca** [comment] 2020-08-18 17:20
> But also doesn't this negate me making a private app and creating the access token? Is there no need for the access token at all then.

Yes, exactly, you don't need an access token for private apps.

> I can create a simple http request using those credentials, but this does not work for the sdk.

I don't know, can you create test case to reproduce the issue? Something like this https://github.com/MONEI/Shopify-api-node/issues/386#issuecomment-668015385.

**Comment by lpinca** [comment] 2020-08-18 17:22
This seems a duplicate of #386.

**Comment by mikeacre** [comment] 2020-08-18 18:11
I dont think its a duplicate.. I am able to access the API with an HTTP call using those credentials. But when I try to use the SDK i get the error, same key and secret from the private app.

But I was also trying to understand how to connect a custom app, and that is why I created the access key... which also didnt work with the sdk it seemed.

**Comment by lpinca** [comment] 2020-08-18 18:42
Try to run this:

```js
const Shopify = require('shopify-api-node');

const shopify = new Shopify({
  shopName: 'quuz',
  apiVersion: '2020-07',
  apiKey: 'b68c3a4bf44cd240511e5f4114f0be4d',
  password: '2d170167fc62551920ca60fe40a5e548'
});

(async function () {
  const shop = await shopify.shop.get();
  console.log(shop);
})().catch(console.error);
```

does it work on your machine? If so replace the `shopName`, `apiKey`, and `password` with your data and check if it works.

**Comment by mikeacre** [comment] 2020-08-19 12:54
`

 HTTPError: Response code 401 (Unauthorized)
     at onResponse (/mnt/c/sites/unalome/console/node_modules/got/dist/source/as-promise/index.js:142:28)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  => awaited here:
     at Function.Promise.await (/home/mikeacre/.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
     at imports/startup/server/shopify.js:33:19
     at /home/mikeacre/.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
   name: 'HTTPError',
   code: undefined,
   timings: {
     start: 1597841516762,
     socket: 1597841516763,
     lookup: 1597841516779,
     connect: 1597841516808,
     secureConnect: 1597841516828,
     upload: 1597841516828,
     response: 1597841516940,
     end: 1597841516943,
     error: undefined,
     abort: undefined,
     phases: {
       wait: 1,
       dns: 16,
       tcp: 29,
       tls: 20,
       request: 0,
       firstByte: 112,
       download: 3,
       total: 181
     }
   }
 }
`

**Comment by mikeacre** [comment] 2020-08-19 12:58
When I load in my credentials I go back to the 

RequestError: Unexpected token < in JSON at position 0

**Comment by lpinca** [comment] 2020-08-19 13:00
Was it run on Meteor? Can you try with plain Node.js?

**Comment by lpinca** [comment] 2020-08-19 13:09
https://runkit.com/5ea585d2c57dcf0013d0bdc2/5f3d23ace5873b001b36cf55

**Comment by mikeacre** [comment] 2020-08-19 13:56
Hey @lpinca you are right, I am using Meteor. I ran this in plain Node and it did work without an issue.

**Comment by mikeacre** [comment] 2020-08-19 13:59
It also works with the access token this way, I guess the issue must be with Meteor or another package I have installed. I will have to play with it. Do you have any ideas?

**Comment by lpinca** [comment] 2020-08-19 14:07
I have no clue. The package was designed for Node.js.

**Comment by jankapunkt** [comment] 2020-08-20 07:19
@mikeacre when putting the example code in a new Meteor project in `server/main.js` then there is no error thrown. Can you please add a minimal reproduction project (with some fake API credentials, that can be replaced with some real ones) where you can reproduce the erorr(s)?

Usually Meteor = Node so there should be no issue with integrating anything that is designed for node.
After getting your issue resolved, we can make a wiki entry in this project, helping others to integrate Shopify with Meteor.

**Comment by mikeacre** [comment] 2020-08-20 10:47
OK Well I figured it out... it is the inclusion of the mailgun-js api. Once I removed that package it worked no problem. I guess I need to look into mailgun now.

const mailgun = require("mailgun-js");

**Comment by lpinca** [comment] 2020-08-20 10:50
On #386 the same issue is caused by `@sentry/node`.

**Comment by lpinca** [comment] 2020-08-21 06:35
Here is a test case with only `mailgun-js` and `got`.

```js
const mailgun = require('mailgun-js');
const got = require('got');

got(
  {
    hostname: 'httpbin.org',
    protocol: 'https:',
    pathname: '/json'
  },
  {
    responseType: 'json',
    retry: 0
  }
)
  .then(function (response) {
    console.log(response.body);
  })
  .catch(console.error);
```

See also https://github.com/highlycaffeinated/mailgun-js/issues/265.

I think this happens because `mailgun-js` uses `proxy-agent` which in turn uses `agent-base@4.3.0` that monkey patches `https.request()` in an incompatible way.

**Comment by lpinca** [comment] 2020-10-23 08:36
I'm closing as switching to `nodemailer` is a viable solution as per https://github.com/MONEI/Shopify-api-node/issues/406#issuecomment-690404955.

**Closed by lpinca** 2020-10-23 08:36 UTC

**Comment by satyavh** [comment] 2020-12-22 13:13
`node-mailjet` has the same issue. As mailjet is owned by mailgun it probably shares the same buggy code
