### ISSUE TITLE
Can't use await

### ISSUE THREAD

**Issue by lacabra-dev** [MONEI/Shopify-api-node#570] opened 2023-01-18 09:50 UTC
Hi everyone

why can I do the following 

`shopifyStore.product
          .get(product.id)
          .then((result) => {
             console.log(result);
          })
          .catch((error) => {
            console.error(error);
          });
`

But I cannot do this: 
`const result = await shopifyStore.product.get(product.id);` ?
I get 

node_modules/got/dist/source/as-promise/index.js:118
                    request._beforeError(new types_1.HTTPError(response));
                                         ^
HTTPError: Response code 404 (Not Found)

**Comment by lpinca** [comment] 2023-01-18 16:04
I can't reproduce.

```
$ cat index.mjs
import Shopify from 'shopify-api-node';

const shopify = new Shopify({
  shopName: 'quuz',
  apiVersion: '2023-01',
  apiKey: 'b68c3a4bf44cd240511e5f4114f0be4d',
  password: '2d170167fc62551920ca60fe40a5e548'
});

const products = await shopify.product.list();

console.log(products);
```

```
$ node index.mjs
[]
```

**Comment by lacabra-dev** [comment] 2023-01-18 16:09
Thanks for the prompt response ! :) 

What if it doesnt? I'll check shortly, but I mean if I query for a product and it cant find it, I'd expect the return to be an empty array just like the .list(), why would it be a 404?

**Comment by lpinca** [comment] 2023-01-18 16:12
> why would it be a 404?

Because 404 is what the API returns for something that does not exist. That is APIs standard behavior.

**Comment by lpinca** [comment] 2023-01-18 19:01
I'm closing this as answered.

**Closed by lpinca** 2023-01-18 19:01 UTC
