### ISSUE TITLE
ESOCKETTIMEDOUT or ECONNRESET errors when fetching orders from some shops

### ISSUE THREAD

**Issue by ganeshkbhat** [MONEI/Shopify-api-node#128] opened 2017-06-06 09:19 UTC
I am getting ESOCKETTIMEDOUT or ECONNRESET errors when connecting from NodeJS using the api. Sometimes this error comes directly and sometimes after an error Unexpected end of JSON input. 

The first error sockettimedout consistently occurs for some shops. The second error is inconsitent and I have ensured that the number of orders I am fetching is 50 and not 250. Second I have also tried replacing the single quotes to doublequotes since I read from somewhere that it could be due to that issue as well. This is the function I am using and the error I am facing. I have removed the details to hide private data that is all.

`let escapeQuoter = function (str) { str = str.replace(/'/g, "\\\'"); str = str.replace(/\\"/g, '\\\\"'); return str; }`

**ERROR: ESOCKETTIMEDOUT**

` Error Fetching Orders Error {\"code\":\"ESOCKETTIMEDOUT\",\"message\":\"Socket timed out on request to xxxx.myshopify.com\",\"hostname\":\"xxxx.myshopify.com\",\"method\":\"GET\",\"path\":\"/admin/orders.json?updated_at_min=2017-03-08T03%3A21%3A28-05%3A00&updated_at_max=2017-06-06T04%3A21%3A28-04%3A00&status=any&page=1&limit=50\"}","timestamp":"2017-06-06T08:24:24.621Z"`

**ERROR: ECONNRESET**

`Error Fetching Orders Error {\"code\":\"ECONNRESET\",\"message\":\"socket hang up\",\"hostname\":\"xxxx.myshopify.com\",\"method\":\"GET\",\"path\":\"/admin/orders.json?updated_at_min=2017-03-08T03%3A20%3A58-05%3A00&updated_at_max=2017-06-06T04%3A20%3A58-04%3A00&status=any&page=1&limit=50\"}","timestamp":"2017-06-06T08:24:27.125Z"`

**"ERROR: Unexpected end of JSON input"**

`Error Fetching Orders Error {\"message\":\"Unexpected end of JSON input in \\\"https://xxxx.myshopify.com\\\": \\n{\\\"orders\\\":[{\\\"id\\\":xxxxx,\\\"email\\\":\\\"xxxx@gmail.com\\\",\\\"closed_at\\\":null...\",\"hostname\":\"xxxx.myshopify.com\",\"method\":\"GET\",\"path\":\"/admin/orders.json?updated_at_min=2017-03-08T03%3A21%3A28-05%3A00&updated_at_max=2017-06-06T04%3A21%3A28-04%3A00&status=any&page=1&limit=50\",\"statusCode\":200,\"statusMessage\":\"OK\"}","timestamp":"2017-06-06T08:24:24.224Z"`

What is the error due to? I have checked autoLimit and my settings are **autoLimit: { calls: 2, interval: 1000 }** so not sure if there is something else thats the issue.

**Comment by lpinca** [comment] 2017-06-06 12:11
The first two are network issues. The last one is caused by malformed JSON sent by the server.
Unfortunately there isn't anything actionable to do apart from retrying the request.

**Comment by lpinca** [comment] 2017-06-09 12:33
Closing, feel free to continue discussing on the closed thread.

**Closed by lpinca** 2017-06-09 12:33 UTC

**Comment by ganeshkbhat** [comment] 2017-06-09 13:32
No the answer is fair enough. Let me check if that was the case possibly. Thank you for your time.

**Comment by aleczratiu** [comment] 2019-04-22 12:42
Increase server timeout
