### ISSUE TITLE
fulfillment.createV2 "errors":"The api_client does not have the required permission(s)." 

### ISSUE THREAD

**Issue by kristiandm** [MONEI/Shopify-api-node#588] opened 2023-03-08 12:20 UTC
Hello, I'm kinda new to using this library and I'm still confused on how to use createV2. We've been using create for some time now but since the 2023-01 update requires us to use createV2 we're trying to switch over our function usage. 

I tried using it this way

const shopify = new Shopify({
shopName: merchant.domain,
apiVersion: '2023-01',
accessToken: merchant.shopifyToken,
});

    shopify.fulfillment.createV2({
              notify_customer: false,
              location_id: inventoryLocation?.id,
              order_id: order.orderId,
              line_items_by_fulfillment_order: [
                {
                  fulfillment_order_id: order.id,                    
                    ...(targetMerchant.serviceType === ServiceType.MARKETPLACE
                      ? {
                        ffulfillment_order_id: order.id,                    
                        ...(targetMerchant.serviceType === ServiceType.MARKETPLACE
                          ? {
                            fulfillment_order_line_items: [{id: order.items.map((item: OrderItems) => {
                              return { id: item.id };
                            }), quantity: order.items.map((itemQuantity: OrderItems) => {
                              return { quantity: toNumber(itemQuantity.quantity) };
                            })}]
                            
                            }
                          : null) 
                }
              ]
            })
            
            but I received this error: "Shopify Open Fulfillment: {"errors":"The api_client does not have the required permission(s)."} , Order ID: 5b1707b0-5908-49a4-9372-9343c163715c , Merchant ID: 55530553543 , Error Message: Response code 403 (Forbidden)"

Can anyone tell me what I did wrong in this code and how to fix it? I would greatly appreciate your help thanks.

**Comment by lpinca** [comment] 2023-03-08 20:41
The error says it is a permission issue. I would check the [access scopes](https://shopify.dev/docs/api/usage/access-scopes).

**Comment by seymurcrisp** [comment] 2023-04-01 15:47
@kristiandm from the admin you can only request access to the protected customer data. The access scopes on the other hand are usually found in the environment file of the app's code.

**Comment by kristiandm** [comment] 2023-04-03 02:57
@seymurcrisp I found a document regarding updating the access scopes using request_granular_access_scopes, but when I tried I can't seem to make it work, I'm getting an html response, do you know what format the request url and payload, and/or headers needs? or can you point me where I can find these information? 

The payload I used was:
{
  "requested_scopes": [
    "write_assigned_fulfillment_orders"
  ]
}

and the request url I used was in this format:
https://API-KEY:SECRET-KEY@shop-name.myshopify.com/admin/request_granular_access_scopes.json

**Comment by lpinca** [comment] 2024-01-13 15:01
I'm closing this because it is not caused by an issue in the library.

**Closed by lpinca** 2024-01-13 15:01 UTC
