### ISSUE TITLE
Cursor-based

### ISSUE THREAD

**Issue by Bek81** [MONEI/Shopify-api-node#303] opened 2019-09-11 15:07 UTC
Using the old shopify API version, I implemented a method that returns a JSON containing some basic info of all the products in the catalog, based on the page count and pagination.
Do you have the instructions how to migrate using the Cursor-based method?

Thanks and regards.

**Comment by lpinca** [comment] 2019-09-15 13:04
Duplicate of #292.

We do not return response headers so there is currently no work around.

**Closed** 2019-11-03 13:16 UTC
